const items = [
    {
        id: '001',
        image: '../images/1.webp',
        company: 'Carlton London',
        item_name: 'Teardrop Shaped Drop Earrings',
        original_price: 1645,
        current_price: 648,
        discount_percentage: 61,
        return_period: 7,
        delivery_date: '09 Jun 2026',
        rating: {
            stars: 4.4,
            count: 52,
        },
    },
    {
        id: '002',
        image: '../images/2.webp',
        company: 'Tokyo Talkies',
        item_name: 'Blue & Pink Floral Printed Square Neck Puff Sleeve Fit & Flare Dress',
        original_price: 2349,
        current_price: 258,
        discount_percentage: 89,
        return_period: 7,
        delivery_date: '11 Jun 2026',
        rating: {
            stars: 4.3,
            count: 60,
        },
    },
    {
        id: '003',
        image: '../images/3.webp',
        company: 'NYPA',
        item_name: 'Women Abstract Printed Flared Cotton Maxi Skirts',
        original_price: 2999,
        current_price: 843,
        discount_percentage: 72,
        return_period: 7,
        delivery_date: '12 Jun 2026',
        rating: {
            stars: 4.3,
            count: 98,
        },
    },
    {
        id: '004',
        image: '../images/4.jpg',
        company: 'ADIDAS',
        item_name: 'Men Indian Cricket One Day International Jersey',
        original_price: 5999,
        current_price: 5999,
        discount_percentage: 0,
        return_period: 7,
        delivery_date: '12 Jun 2026',
        rating: {
            stars: 4.6,
            count: 532,
        },
    },
    {
        id: '005',
        image: '../images/5.webp',
        company: 'Roadster',
        item_name: 'Time Travel Men Teal Blue Printed Cotton T-shirt',
        original_price: 599,
        current_price: 369,
        discount_percentage: 38,
        return_period: 7,
        delivery_date: '12 Jun 2026',
        rating: {
            stars: 4,
            count: 8800,
        },
    },
    {
        id: '006',
        image: '../images/6.webp',
        company: 'Nike',
        item_name: "Women Textile Running Non-Marking Shoes",
        original_price: 4295,
        current_price: 3436,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '12 Jun 2026',
        rating: {
            stars: 0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '../images/7.webp',
        company: 'U.S Polo Assn.',
        item_name: 'Men Lounge Shorts',
        original_price: 999,
        current_price: 719,
        discount_percentage: 28,
        rating: {
            stars: 4.3,
            count: 2100,
        },
    },
    {
        id: '008',
        image: '../images/8.webp',
        company: 'Marks & Spencer',
        item_name: 'Seasalt & Neroli Long Lasting Eau De Toilette 30ml',
        original_price: 799,
        current_price: 599,
        discount_percentage: 25,
        return_period: 0,
        delivery_date: '12 Jun 2026',
        rating: {
            stars: 4.3,
            count: 74,
        },
    }
];